### ISSUE TITLE
Problem using SignInWithEmailAndPassword

### ISSUE THREAD

**Issue by lucwuyts** [step-up-labs/firebase-authentication-dotnet#4] opened 2016-09-22 14:09 UTC
Just starting with Firebase, and discovered your posts and libraries.
When i have my rules set to anonymous access (write and read), i can post to the database.

When i try with a email login, i always get the error:  {  "error" : "Could not parse auth token." }
auth.user shows the correct email and Id.

This is the code i'm using:

```
        var firebase = new FirebaseClient(databaseUrl);
        var authProvider = new FirebaseAuthProvider(new FirebaseConfig(apiKey));      

        var auth = await authProvider.SignInWithEmailAndPasswordAsync( xxxx , yyyy );

        var db = firebase
            .Child("SanPrg2")
            .WithAuth( auth.FirebaseToken );

        var d = new Dinosaur { Height = 20 };
        await db.PostAsync(d);
```

**Comment by Ravalesh** [comment] 2016-11-09 11:06
Was having similar issue. Had to send an additional parameter to PostAsync; bool value of false.

**Comment by joanlopez** [comment] 2016-11-10 07:05
Hi @Ravalesh,
I'm having the same problem...
Can you explain your solution in a more verbose way?
Thanks! 👍

**Comment by Ravalesh** [comment] 2016-11-10 07:19
try this:

 var account = new Accounts();

            account.Name = "jj";
            account.Email = "jj@g.com";

            var authProvider = new FirebaseAuthProvider(new FirebaseConfig(<API KEY>));
            FirebaseAuth auth = await authProvider.SignInWithEmailAndPasswordAsync(<Email>, <Password>);

            var firebase = new FirebaseClient("<Firebase URL>");


            var accounts = await firebase
                .Child("users")
              .WithAuth(auth.FirebaseToken)
               .PostAsync(account, false);

The extra parameter(generate key offline) in the PostAsync method solved the issue. 
I guess when the key is generated offline, it would make the request URL very large and the HTTP request handler will not be handle that.

**Comment by bezysoftware** [comment] 2016-11-11 10:09
Duplicate of https://github.com/step-up-labs/firebase-database-dotnet/issues/22

**Closed by bezysoftware** 2016-11-11 10:09 UTC

**Comment by joanlopez** [comment] 2016-11-15 08:08
Finally it worked for me!

Thanks!

PD: Sorry for replying on an replicated issue
