### ISSUE TITLE
Email Verification Not Working

### ISSUE THREAD

**Issue by kashifiqbal112** [step-up-labs/firebase-authentication-dotnet#29] opened 2017-06-17 15:43 UTC
IsEmailVerified Always Return False even if i verify email from my inbox

**Comment by bezysoftware** [comment] 2017-06-25 13:39
Duplicate of #21

**Closed by bezysoftware** 2017-06-25 13:39 UTC

**Comment by kashifiqbal112** [comment] 2017-06-25 14:18
what is the Solution ?

**Comment by musimate** [comment] 2017-07-19 15:59
I'm experiencing the same.

**Comment by drptbl** [comment] 2018-01-30 15:09
Solution found in #21
